import Link from 'next/link';
import Footer from '../components/Footer';

export const metadata = {
  title: 'AI Visibility for Ecommerce | Will Your Products Appear in AI Shopping Answers? | The Hub Content',
  description: 'Ecommerce brands are losing sales to AI shopping assistants that can\'t find their product pages. Run a free AI Visibility audit and see exactly why your store is invisible to ChatGPT, Perplexity, and Google AI Overviews.',
  robots: 'index, follow',
  metadataBase: new URL('https://ai-visibility.thehubcontent.com'),
  alternates: { canonical: '/ecommerce' },
  openGraph: {
    title: 'AI Visibility for Ecommerce | The Hub Content',
    description: 'See if AI shopping assistants can find and cite your product pages. Free audit tool for ecommerce brands.',
    url: 'https://ai-visibility.thehubcontent.com/ecommerce',
    type: 'website',
  },
};

const faqs = [
  {
    q: 'Why are my products not appearing in ChatGPT shopping answers?',
    a: `ChatGPT's OAI-SearchBot crawls product pages in real time to generate shopping recommendations. If your robots.txt blocks OAI-SearchBot, or your product content is rendered via JavaScript (invisible to most crawlers), your products will never appear in AI-generated shopping comparisons. The most common fix is to ensure OAI-SearchBot is explicitly allowed in robots.txt and that your product schema (Product, Offer, AggregateRating JSON-LD) is in the raw HTML response.`,
  },
  {
    q: 'What structured data do AI assistants look for on ecommerce product pages?',
    a: `AI answer engines primarily extract Schema.org Product markup — specifically the name, description, offers (price, availability, currency), aggregateRating, and brand fields. Perplexity and ChatGPT both use these signals to construct inline product cards and comparison tables. Without JSON-LD Product schema, your products are treated as anonymous web text with no structured signals, dramatically reducing citation probability.`,
  },
  {
    q: 'How does Perplexity AI discover ecommerce products?',
    a: `Perplexity's crawler (PerplexityBot) indexes pages and generates its shopping answers by combining extracted text content with structured data signals. For ecommerce, Perplexity prioritizes pages with: (1) clear product name in H1, (2) price visible in raw HTML, (3) Product schema with Offer markup, (4) fast TTFB under 400ms, and (5) no JavaScript dependency for core product text. Pages that score well on these signals are more likely to appear in Perplexity shopping answer citations.`,
  },
  {
    q: 'What is the difference between Google AI Overviews and traditional Google Shopping?',
    a: `Traditional Google Shopping uses Google Merchant Center product feeds and paid/organic Shopping ads. Google AI Overviews are generated by Gemini models that crawl and synthesize web content in real time. AI Overviews cite editorial product reviews, comparison articles, and product pages with strong entity signals — not just Merchant Center feeds. To appear in AI Overviews, your product pages need high-quality descriptive text, clear brand entity markup, and strong E-E-A-T signals alongside traditional SEO.`,
  },
  {
    q: 'Does blocking GPTBot hurt my ecommerce AI visibility?',
    a: `Blocking GPTBot only prevents OpenAI from using your content to train future models — it does NOT block ChatGPT from citing your pages in live search answers. ChatGPT's live web search uses OAI-SearchBot, which is a separate crawler. However, blocking OAI-SearchBot will remove your products from ChatGPT's real-time web search entirely. For most ecommerce brands, the recommended approach is: block GPTBot to protect your content from training data, but explicitly allow OAI-SearchBot for live citation indexing.`,
  },
  {
    q: 'How can I optimize my product category pages for AI visibility?',
    a: `Category pages are often overlooked in AI optimization. To maximize AI visibility for category pages: (1) Write a 150-200 word introductory paragraph explaining what the category covers — AI crawlers need semantic context to classify and cite category pages. (2) Add BreadcrumbList schema to help AI understand site taxonomy. (3) Use ItemList schema for product listings. (4) Ensure category page text renders in raw HTML, not JavaScript. (5) Link to your top-reviewed products prominently — AI systems follow internal link graphs to discover authoritative product content.`,
  },
];

const schema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: faqs.map((f) => ({
    '@type': 'Question',
    name: f.q,
    acceptedAnswer: { '@type': 'Answer', text: f.a },
  })),
};

export default function EcommerceLandingPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <div style={{ minHeight: '100vh', background: 'var(--bg, #0d0e12)', color: 'var(--ink, #e8eaf0)', fontFamily: 'var(--font-sans, system-ui)' }}>

        {/* ── NAV ─────────────────────────────────────────────────── */}
        <nav style={{ borderBottom: '1px solid rgba(255,255,255,0.07)', padding: '16px 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', position: 'sticky', top: 0, background: 'rgba(13,14,18,0.92)', backdropFilter: 'blur(12px)', zIndex: 100 }}>
          <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: '10px', textDecoration: 'none' }}>
            <img src="/logo_processed.png" alt="AI Visibility Checker" width={28} height={28} style={{ borderRadius: '50%' }} />
            <span style={{ fontFamily: 'var(--font-serif, Georgia)', fontWeight: 600, color: '#fff', fontSize: '15px' }}>AI Visibility Checker</span>
          </Link>
          <Link href="/" style={{ fontSize: '13px', color: 'var(--ink-soft, #8b8fa8)', textDecoration: 'none', border: '1px solid rgba(255,255,255,0.12)', padding: '7px 16px', borderRadius: '6px', transition: 'all 0.15s' }}>
            ← Run Free Audit
          </Link>
        </nav>

        {/* ── HERO ────────────────────────────────────────────────── */}
        <header style={{ maxWidth: '820px', margin: '0 auto', padding: '80px 24px 60px', textAlign: 'center' }}>
          <div style={{ display: 'inline-block', background: 'rgba(99,102,241,0.12)', border: '1px solid rgba(99,102,241,0.3)', borderRadius: '20px', padding: '6px 14px', fontSize: '12px', color: '#818cf8', fontFamily: 'var(--font-mono, monospace)', letterSpacing: '0.08em', marginBottom: '24px' }}>
            ECOMMERCE · AEO AUDIT
          </div>
          <h1 style={{ fontSize: 'clamp(2rem, 5vw, 3.25rem)', fontFamily: 'var(--font-serif, Georgia)', fontWeight: 600, lineHeight: 1.15, marginBottom: '20px', letterSpacing: '-0.02em' }}>
            AI Visibility for<br />
            <span style={{ background: 'linear-gradient(135deg, #818cf8 0%, #a78bfa 100%)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>Ecommerce Brands</span>
          </h1>
          <p style={{ fontSize: '18px', color: 'var(--ink-soft, #8b8fa8)', lineHeight: 1.7, maxWidth: '600px', margin: '0 auto 36px' }}>
            Shoppers are asking ChatGPT, Perplexity, and Google AI Overviews which products to buy. If your store isn't indexed by AI crawlers, you're invisible to them — and losing sales to competitors who are.
          </p>
          <Link href="/" style={{ display: 'inline-block', background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)', color: '#fff', padding: '14px 32px', borderRadius: '8px', fontWeight: 600, fontSize: '15px', textDecoration: 'none', boxShadow: '0 4px 20px rgba(99,102,241,0.35)' }}>
            Audit Your Ecommerce Site Free →
          </Link>
        </header>

        {/* ── SIGNALS GRID ────────────────────────────────────────── */}
        <section style={{ maxWidth: '900px', margin: '0 auto', padding: '0 24px 80px' }}>
          <h2 style={{ textAlign: 'center', fontFamily: 'var(--font-serif, Georgia)', fontSize: '1.6rem', marginBottom: '40px', fontWeight: 600 }}>
            What AI Shopping Assistants Check on Your Store
          </h2>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))', gap: '20px' }}>
            {[
              { icon: '🤖', title: 'AI Crawler Access', body: 'Is OAI-SearchBot (ChatGPT), PerplexityBot, and ClaudeBot allowed to index your product pages? Blocked bots = zero citations.' },
              { icon: '🏷️', title: 'Product Schema (JSON-LD)', body: 'Product, Offer, and AggregateRating markup tells AI systems exactly what you sell, at what price, and with what social proof.' },
              { icon: '📄', title: 'Raw HTML Content', body: 'Product descriptions rendered client-side via JavaScript are invisible to most AI crawlers. Text must be in the initial HTML response.' },
              { icon: '⚡', title: 'Page Speed (TTFB)', body: 'AI crawlers time-out on slow pages. A Time to First Byte under 400ms is the threshold for reliable AI crawler indexing.' },
              { icon: '📖', title: 'Readability Score', body: 'Flesch Reading Ease 60–80 is optimal for AI extraction. Dense, technical prose is harder for LLMs to summarize and cite accurately.' },
              { icon: '🔗', title: 'Internal Link Graph', body: 'AI systems traverse your internal links to discover and build context on your brand. Orphaned product pages are rarely cited.' },
            ].map((card) => (
              <div key={card.title} style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', borderRadius: '12px', padding: '24px' }}>
                <div style={{ fontSize: '28px', marginBottom: '12px' }}>{card.icon}</div>
                <h3 style={{ fontWeight: 600, fontSize: '15px', marginBottom: '8px', color: '#e8eaf0' }}>{card.title}</h3>
                <p style={{ fontSize: '13px', color: 'var(--ink-soft, #8b8fa8)', lineHeight: 1.65, margin: 0 }}>{card.body}</p>
              </div>
            ))}
          </div>
        </section>

        {/* ── FAQ SECTION ─────────────────────────────────────────── */}
        <section style={{ maxWidth: '760px', margin: '0 auto', padding: '0 24px 80px' }}>
          <h2 style={{ fontFamily: 'var(--font-serif, Georgia)', fontSize: '1.6rem', marginBottom: '40px', fontWeight: 600, textAlign: 'center' }}>
            Ecommerce AI Visibility: Questions &amp; Answers
          </h2>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '28px' }}>
            {faqs.map((faq, i) => (
              <div key={i} style={{ borderLeft: '3px solid rgba(99,102,241,0.4)', paddingLeft: '20px' }}>
                <h3 style={{ fontSize: '16px', fontWeight: 600, marginBottom: '10px', color: '#e8eaf0', lineHeight: 1.45 }}>{faq.q}</h3>
                <p style={{ fontSize: '14px', color: 'var(--ink-soft, #8b8fa8)', lineHeight: 1.75, margin: 0 }}>{faq.a}</p>
              </div>
            ))}
          </div>
        </section>

        {/* ── CTA BANNER ──────────────────────────────────────────── */}
        <section style={{ background: 'linear-gradient(135deg, rgba(99,102,241,0.12) 0%, rgba(139,92,246,0.08) 100%)', border: '1px solid rgba(99,102,241,0.2)', borderRadius: '16px', maxWidth: '760px', margin: '0 auto 80px', padding: '48px 32px', textAlign: 'center' }}>
          <h2 style={{ fontFamily: 'var(--font-serif, Georgia)', fontSize: '1.8rem', fontWeight: 600, marginBottom: '16px' }}>
            Is Your Ecommerce Store AI-Ready?
          </h2>
          <p style={{ color: 'var(--ink-soft, #8b8fa8)', fontSize: '15px', marginBottom: '28px', lineHeight: 1.65 }}>
            Run a free 80-metric AI Visibility audit on any product URL or store homepage in under 60 seconds.
          </p>
          <Link href="/" style={{ display: 'inline-block', background: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)', color: '#fff', padding: '14px 32px', borderRadius: '8px', fontWeight: 600, fontSize: '15px', textDecoration: 'none' }}>
            Free Ecommerce AI Audit →
          </Link>
        </section>

        <Footer />
      </div>
    </>
  );
}
