/**
 * exportReport.js
 * Utilities for formatting and triggering browser downloads of AI Visibility Audit Reports
 * in Markdown (.md) and CSV (.csv) formats.
 */

/**
 * Generates a full Markdown report matching the THC AI Visibility Audit specification.
 */
export function generateMarkdownReport(result) {
  if (!result) return '';

  const url = result.url || 'Target Site';
  const score = result.finalScore ?? 'N/A';
  const grade = result.grade || 'N/A';
  const gradeMeaning = result.gradeMeaning || '';
  const scannedAt = result.scannedAt ? new Date(result.scannedAt).toUTCString() : new Date().toUTCString();

  const categories = result.categoryDetails || [];
  const conflicts = result.criticalConflicts || [];
  const recs = result.recommendations || [];
  const signals = result.signals || {};

  let md = `# AI Visibility & GEO Audit Report

**Target URL**: \`${url}\`  
**Overall AI Visibility Score**: **${score} / 100** (Grade ${grade} — *${gradeMeaning}*)  
**Audit Timestamp**: \`${scannedAt}\`  

---

## 1. Executive Category Breakdown

| Category | Score | Weight | Assessment |
| :--- | :---: | :---: | :--- |
${categories.map(c => `| **${c.name}** | **${c.score}/100** | ${c.weight}% | ${c.score >= 80 ? '✅ Pass' : c.score >= 65 ? '⚠️ Warning' : '❌ Fail'} |`).join('\n')}

---

## 2. Priority Action Plan & Recommendations

${recs.length > 0 ? recs.map((r, i) => `
### ${i + 1}. [${r.priority || 'P1'}] ${r.title}
* **Category**: ${r.category || 'General'}
* **Impact**: ${r.impact || 'Medium'} | **Effort**: ${r.effort || 'Low'}
* **Affected**: \`${r.affected || 'sitewide'}\`
* **Remediation**: ${r.fix || 'No specific fix instructions.'}
`).join('\n') : '*No open high-priority issues detected.*'}

---

## 3. Detected Conflicts & Risk Flags

${conflicts.length > 0 ? conflicts.map(c => `
> [!${c.severity === 'CRITICAL' ? 'CAUTION' : 'WARNING'}]
> **${c.title}**  
> **Evidence**: \`${c.evidence}\`  
> **Fix**: ${c.fix}
`).join('\n\n') : '*Zero cross-signal conflicts detected.*'}

---

## 4. Deep Technical Telemetry

### A. AI Crawler Access & Robots.txt
* **Answer Engine Access Status**: ${result.isAnswerBotBlocked ? '❌ **BLOCKED** (Critical AI citation bots disallowed)' : '✅ **ALLOWED**'}
* **llms.txt Map Status**: ${signals.llmsTxt?.found ? `✅ Discovered (${signals.llmsTxt.linkCount || 0} links mapped)` : '⚠️ Not Found'}
* **Declared Sitemap Line**: \`${signals.robots?.sitemapUrl || 'None declared in robots.txt'}\`

### B. Structured Data & Entity Linking
* **Schemas Detected**: \`${(signals.html?.structuredData?.schemaTypes || []).join(', ') || 'None'}\`
* **Knowledge Graph Entity Links (\`sameAs\`)**: ${signals.html?.structuredData?.entityLinking?.count || 0} links verified
* **Schema \`@id\` Graph Nodes**: ${signals.html?.entitySignals?.schemaNodeIdsCount || 0} nodes defined

### C. Content Structure & Extractability
* **Flesch Reading Ease**: ${signals.html?.readability?.readingEase ?? 'N/A'}/100 (${signals.html?.readability?.readingEaseLabel || 'NA'})
* **H1 Count**: ${signals.html?.headings?.h1Count ?? 0} | **Heading Hierarchy Skips**: ${signals.html?.headings?.hasSkippedLevels ? 'Yes ❌' : 'Clean ✅'}
* **Content-to-Code Ratio**: ${signals.html?.browserSignals?.contentToCodeRatio ?? 0}%

### D. Technical Performance & Core Web Vitals
* **Native Server TTFB**: ${signals.pageSpeed?.nativeTiming?.ttfbMs != null ? `${signals.pageSpeed.nativeTiming.ttfbMs}ms` : 'N/A'}
* **LCP (Largest Contentful Paint)**: ${signals.pageSpeed?.mobile?.cwv?.lcp || 'N/A'}
* **TBT (Total Blocking Time)**: ${signals.pageSpeed?.mobile?.cwv?.tbt || 'N/A'}
* **CLS (Cumulative Layout Shift)**: ${signals.pageSpeed?.mobile?.cwv?.cls || 'N/A'}

---

## Appendix: Reference Configuration Templates

### Sample \`robots.txt\` for AI Search Allow:
\`\`\`
User-agent: *
Allow: /

# Allow AI Citation & Search Engines
User-agent: OAI-SearchBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Claude-SearchBot
Allow: /

Sitemap: ${url.replace(/\/$/, '')}/sitemap.xml
\`\`\`

### Sample \`/llms.txt\` Navigation Map:
\`\`\`markdown
# ${url.replace(/^https?:\/\//, '').replace(/\/$/, '')}

> Comprehensive machine-readable summary for LLM context windows.

## Core Content & Documentation
- [Homepage](${url}): Primary entity landing page.
- [Sitemap](${url.replace(/\/$/, '')}/sitemap.xml): XML index for crawling.
\`\`\`

*Report generated by THC AI Visibility Auditor (v1.0)*
`;

  return md.trim();
}

/**
 * Generates CSV audit summary data matching standard tabular schema.
 */
export function generateCsvReport(result) {
  if (!result) return '';

  const headers = ['URL', 'AI Visibility Score', 'Grade', 'AI Crawler Access', 'Structured Data', 'Content Structure', 'Performance', 'Metadata Hygiene', 'Answer Bot Blocked', 'Open Issues Count'];
  const row = [
    `"${result.url || ''}"`,
    result.finalScore ?? '',
    `"${result.grade || ''}"`,
    result.categoryScores?.aiCrawlerAccess ?? '',
    result.categoryScores?.structuredData ?? '',
    result.categoryScores?.contentExtractability ?? '',
    result.categoryScores?.performance ?? '',
    result.categoryScores?.metadataHygiene ?? '',
    result.isAnswerBotBlocked ? 'TRUE' : 'FALSE',
    (result.recommendations || []).length
  ];

  let csv = headers.join(',') + '\n' + row.join(',') + '\n\n';

  csv += 'Priority,Issue,Category,Affected,Effort,Remediation\n';
  (result.recommendations || []).forEach(r => {
    csv += `"${r.priority || 'P1'}","${(r.title || '').replace(/"/g, '""')}","${(r.category || '').replace(/"/g, '""')}","${(r.affected || '').replace(/"/g, '""')}","${(r.effort || '').replace(/"/g, '""')}","${(r.fix || '').replace(/"/g, '""')}"\n`;
  });

  return csv;
}

/**
 * Triggers a browser file download for a given string content.
 */
export function downloadFile(content, fileName, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
